export interface NigeriaState {
  name: string
  cities: string[]
}

export const NIGERIA_STATES: NigeriaState[] = [
  { name: 'Abia', cities: ['Umuahia', 'Aba', 'Ohafia', 'Arochukwu'] },
  { name: 'Adamawa', cities: ['Yola', 'Mubi', 'Numan', 'Ganye'] },
  { name: 'Akwa Ibom', cities: ['Uyo', 'Ikot Ekpene', 'Eket', 'Oron'] },
  { name: 'Anambra', cities: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia'] },
  { name: 'Bauchi', cities: ['Bauchi', 'Azare', 'Misau', 'Katagum'] },
  { name: 'Bayelsa', cities: ['Yenagoa', 'Ogbia', 'Brass', 'Sagbama'] },
  { name: 'Benue', cities: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala'] },
  { name: 'Borno', cities: ['Maiduguri', 'Biu', 'Dikwa', 'Gubio'] },
  { name: 'Cross River', cities: ['Calabar', 'Ikom', 'Ogoja', 'Obubra'] },
  { name: 'Delta', cities: ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor'] },
  { name: 'Ebonyi', cities: ['Abakaliki', 'Afikpo', 'Onueke', 'Ezza'] },
  { name: 'Edo', cities: ['Benin City', 'Auchi', 'Ekpoma', 'Uromi'] },
  { name: 'Ekiti', cities: ['Ado-Ekiti', 'Ikere-Ekiti', 'Emure-Ekiti', 'Ise-Ekiti'] },
  { name: 'Enugu', cities: ['Enugu', 'Nsukka', 'Onitsha-Ugbo', 'Udi'] },
  { name: 'FCT', cities: ['Abuja', 'Gwagwalada', 'Kuje', 'Bwari', 'Kwali', 'Abaji'] },
  { name: 'Gombe', cities: ['Gombe', 'Deba', 'Kaltungo', 'Bajoga'] },
  { name: 'Imo', cities: ['Owerri', 'Orlu', 'Okigwe', 'Oguta'] },
  { name: 'Jigawa', cities: ['Dutse', 'Hadejia', 'Gumel', 'Kazaure'] },
  { name: 'Kaduna', cities: ['Kaduna', 'Zaria', 'Kafanchan', 'Kagoro'] },
  { name: 'Kano', cities: ['Kano', 'Wudil', 'Bichi', 'Gwarzo', 'Rano'] },
  { name: 'Katsina', cities: ['Katsina', 'Daura', 'Funtua', 'Mashi'] },
  { name: 'Kebbi', cities: ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru'] },
  { name: 'Kogi', cities: ['Lokoja', 'Okene', 'Kabba', 'Ankpa'] },
  { name: 'Kwara', cities: ['Ilorin', 'Offa', 'Omu-Aran', 'Pategi'] },
  { name: 'Lagos', cities: ['Lagos Island', 'Lagos Mainland', 'Ikeja', 'Surulere', 'Lekki', 'Victoria Island', 'Yaba', 'Apapa', 'Epe', 'Ikorodu', 'Badagry', 'Oshodi', 'Alimosho', 'Ajah'] },
  { name: 'Nasarawa', cities: ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa'] },
  { name: 'Niger', cities: ['Minna', 'Suleja', 'Bida', 'Kontagora'] },
  { name: 'Ogun', cities: ['Abeokuta', 'Sagamu', 'Ijebu-Ode', 'Ota', 'Ilaro'] },
  { name: 'Ondo', cities: ['Akure', 'Ondo', 'Owo', 'Ikare', 'Ore'] },
  { name: 'Osun', cities: ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo'] },
  { name: 'Oyo', cities: ['Ibadan', 'Ogbomosho', 'Oyo', 'Iseyin', 'Saki'] },
  { name: 'Plateau', cities: ['Jos', 'Bukuru', 'Pankshin', 'Shendam'] },
  { name: 'Rivers', cities: ['Port Harcourt', 'Bonny', 'Obio-Akpor', 'Eleme', 'Okrika'] },
  { name: 'Sokoto', cities: ['Sokoto', 'Wurno', 'Tambuwal', 'Illela'] },
  { name: 'Taraba', cities: ['Jalingo', 'Wukari', 'Bali', 'Sansanmadi'] },
  { name: 'Yobe', cities: ['Damaturu', 'Potiskum', 'Nguru', 'Gashua'] },
  { name: 'Zamfara', cities: ['Gusau', 'Kaura Namoda', 'Anka', 'Tsafe'] },
]
